---
- name: delete ec2 key
  ec2_key:
    name: "{{ project_name }}-{{ env }}-key"
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    region: "{{ region }}"
    state: absent
  delegate_to: localhost

- name: remove private key
  file:
    path: "roles/aws-ec2-instance/files/{{ project_name }}-{{ env }}-private.pem"
    state: absent
  delegate_to: localhost

- name: remove private key from ansible hosts file
  replace:
    path: hosts
    regexp: '(.*)(ansible_ssh_private_key=.*)'
    replace: '\1'
    after: '[ec2_hosts]'
  delegate_to: localhost
