---
- name: create ec2 key
  ec2_key:
    name: "{{ project_name }}-{{ env }}-key"
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    region: "{{ region }}"
  register: ec2_key

- name: save private key
  copy:
    content: "{{ ec2_key.key.private_key }}"
    dest: "roles/rancher-server/files/{{ project_name}}-{{ env }}-private.pem"
    mode: 0600
  when: ec2_key.changed
