---
- name: delete ec2 key
  ec2_key:
    name: "{{ project_name }}-{{ env }}-key"
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    region: "{{ region }}"
    state: absent

- name: remove private key
  file:
    path: "roles/rancher-server/files/{{ project_name}}-{{ env }}-private.pem"
    state: absent
