---
  - name: delete security group
    ec2_group:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      region: "{{ region }}"
      name: rancher-server-sg
      state: absent
