---
- name: get ec2 instance
  ec2_instance_facts:
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    region: "{{ region }}"
    filters:
      "tag:project": "{{ project_name }}"
      "tag:env": "{{ env }}"
      "instance-state-code": "16"
  register: ec2_instances

- name: terminate ec2 instance
  ec2:
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    region: "{{ region }}"
    state: absent
    instance_ids: "{{ item.instance_id }}"
    wait: true
  with_items: "{{ ec2_instances.instances }}"

- name: remove the instance from ansible hosts file
  lineinfile:
    path: hosts
    regexp: "{{ item.public_ip_address }}"
    state: absent
  with_items: "{{ ec2_instances.instances }}"
