---
  - name: delete security group
    ec2_group:
      aws_access_key: "{{ ec2_access_key }}"
      aws_secret_key: "{{ ec2_secret_key }}"
      region: "{{ region }}"
      group_id: "{{ rancher_server_security_group_id }}"
      state: absent

  - name: remove stored security group information
    file:
      path: group_vars/all/vars_security_group_created.yml
      state: absent
